### PR TITLE
Added ability for subitems to have quantity

### PR DESCRIPTION
**Pull request by jmarcher**
If you want to add subitems with quantity now it gets considered in the subtotal of the item

Lets say:
12" Pizza
     - 2 Salami (as subitem)

### CODE REVIEW

**Comment by lukepolo** [comment]
waiting for the build to test

**Comment by jmarcher** [comment]
Let me fix the styleci errors

**Comment by lukepolo** [comment]
1.1.44 has been released

**Comment by lukepolo** [comment]
Thanks for the great PR's!

**Comment by jmarcher** [comment]
Thank you for the great package

**Pull request merged**
