### PR TITLE
pre tax discount fixes 

### LINKED ISSUE #275: Percentage discount is calculated without taxes [has-pr]
A percentage discount that is unrelated to an item is calculated incorrectly, as it seems the percentage value is calculated from the net and not from the gross, so without taxes. With the variant "Fixed" it seems to be correct.

If a coupon is attached to the item itself, it seems to be true.

### PR DESCRIPTION
**Pull request by lukepolo**
#275

WIP

### CODE REVIEW

**Comment by lukepolo** [comment]
This library is starting to show its date , I cringe when I go through this code 🤣

**Comment by lukepolo** [comment]
@dennisoderwald , if you can, can you test with these fixes?  I added 2 tests and things seem to be working as normal.

**Comment by dennisoderwald** [comment]
@lukepolo Seems like the problem is fixed.

I'm just wondering if `taxTotal()` should be extended to output the taxTotal without discount, because if a taxed discount is deducted, taxTotal should no longer be given after applying the voucher. Or what do you think?

**Comment by lukepolo** [comment]
it probably could be done, I would need to refactor the configs (which needs it anyways) 

Feel free to make PR~

**Pull request merged**
