### PR TITLE
Options not merging with passed in ones.

### PR DESCRIPTION
**Pull request by alvaroenoht**

### CODE REVIEW

**Comment by lukepolo** [comment]
Can you fix up the tests? I they have failed but I believe the tests were written wrong. I can mege and fix if you cannot.

**Comment by alvaroenoht** [comment]
Hi, I did made that change and it works but I have no idea how to fix the test.

**Comment by lukepolo** [comment]
Ok ill merge as soon as I get some time to fix up the tests, I see the issue witht the test already

**Comment by lukepolo** [comment]
#132 

You almost had it right :-)

**Pull request closed without merging**
