### PR TITLE
Add PHP8 to composer.json

### PR DESCRIPTION
**Pull request by daniel-zahariev**

### CODE REVIEW

**Comment by lukepolo** [comment]
can you change the name back to the original? Also add the php 8 to the test env.

**Comment by daniel-zahariev** [comment]
Hi @lukepolo, should be ok now.

**Comment by lukepolo** [comment]
Thanks! Once test passes ill make a release

**Comment by lukepolo** [comment]
One of my deps does not have php 8 quite yet 

https://github.com/codeclimate/php-test-reporter 

Also working on making sure it will actually work in php8

**Comment by lukepolo** [comment]
https://github.com/lukepolo/laracart/releases/tag/1.12.0-RC-1

**Comment by daniel-zahariev** [comment]
Thanks!

**Pull request merged**
