### PR TITLE
Tax can be more than 100%

### PR DESCRIPTION
**Pull request by jmarcher**
There are some cases where you need a tax bigger than 100%

And add a workaround for this: https://github.com/lukepolo/laracart/issues/170#issuecomment-298938912

### CODE REVIEW

**Comment by lukepolo** [comment]
I did not know this! Can you fix the test for this?

**Comment by jmarcher** [comment]
@lukepolo fixed the problem and changed the exception message, i can create another PR to merge this into master if you agree

**Comment by lukepolo** [comment]
Looks good, please create one to merge into master , ill merge asap :-)

**Comment by lukepolo** [comment]
1.1.42 is the release for 1.1 series

**Comment by lukepolo** [comment]
Should have been 1.1.43

**Pull request merged**
